---
title: "Vectors"
author: "cdurso"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Make a vector

```{r}
fib<-c(0,1,2,3,5,8,11)
fib

(twos<-c(1,2,4,8,16,32,64))

(planets<-c("Mercury","Venus","Earth","Mars"))
```

## Compute with numeric vectors

```{r}
0.5*fib
fib+3
fib^2
fib+twos
```
## Concatenate vectors

```{r}
(v<-c(fib,twos))
more<-c("Jupiter","Saturn")
planets<-c(planets,more)
planets
```


## sequences

```{r}
(ints<-0:5)
2^ints
(tenths<-seq(-1,1,by=.1))
(twenty<-seq(-2,2,length.out=20))
seq(5,18,by=6)
2:(-1)
```
## Repetition

```{r}
rep(55,3)
rep(c("a","b"),2)
rep(c("a","b"),each=2)
rep(c("a","b"),c(4,2))

```


## indexing

```{r}
planets[1:3]
planets[2:4]

fib[fib!=1]
twos[twos>=4 & twos<32]
fib[twos>4]
planets[-(2:4)]
```

## Functions with vector arguments

```{r}
sum(fib)
cumsum(1:5)
mean(1:5)
```

## lists

```{r}
stuff<-list("a",TRUE, FALSE,77,88)

(myls <- vector("list", length = 3))
myls[[2]]<-"second"
myls
```

